title: Meta Schema
description: 'For example: <code>url_category</code> would be copied to <code>meta_url_category</code>'
data_fields:
- standard_name: category
  type: string
  description: 'Description to define a grouping of a value. Commonly used for URL/domain
    category (ie: Adult, Abuse, Parked, RFC-1918, etc)'
  sample_value: '``'
- standard_name: ttp
  type: string
  description: Tactic, technique, and procedure
  sample_value: '``'
- standard_name: alert
  type: string
  description: Data describing an alert
  sample_value: '``'
- standard_name: geo location
  type: geo_point
  description: Geo longitude and latitude point of a field
  sample_value: '``'
- standard_name: AS Number
  type: integer
  description: Autonomous System (AS) number (BGP AS Number)
  sample_value: '``'
- standard_name: AS Org
  type: string
  description: Autonomous System (AS) organization (BGP AS Name)
  sample_value: '``'
references: []
tags: []
